name: celery_neuralnets
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - ipykernel
    # pytorch
  - pytorch
  - torchvision
  - cudatoolkit=11.1
    # celery
  - celery==5.1.2
  - watchdog
  #   # neuralnets
  # - future
  # - tensorboard
  # - numpy
  # - tifffile
  # - h5py
  # - scikit-image
  # - progress
  # - six
  # - scikit-learn
  # - opencv==4.2.0
  # for shape_utils
  - plotly
  - pandas
  - cairosvg
  # 
  - pip
  - pip: 
    # - neuralnets
    - git+https://github.com/JorisRoels/neuralnets.git
    # - git+https://github.com/JorisRoels/neuralnets.git@biosegment
    # celery
    - celery[redis]==5.1.2



